### ISSUE TITLE
credits is probably missing a bunch of people

### ISSUE THREAD

**Issue by anarcat** [neomutt/neomutt.github.io#1]
the credits page asks "Who do we thank?" yet doesn't clearly state what criteria is used to add people to the page. It seems to me the original Mutt author ("Michael Elkins" as [per Wikipedia](https://en.wikipedia.org/wiki/Mutt_%28email_client%29)) should be added at least

Ohloh also has a [different list](https://www.openhub.net/p/mutt/contributors?query=&time_span=&sort=commits).

Then of course there's the [acknowledgements](http://www.mutt.org/doc/manual/#acknowledgements) section of the original manual. Maybe a link to that and a mention of Elkins would be sufficient?

**Comment by flatcap** [comment]
Fair point.  The website was thrown together fairly quickly.
The list is all the authors for NeoMutt (which is just a set of feature patches).

When searching for patches/repos I was careful to note down _anyone_ who made any changes to the code.  _They_ are all represented in the list.

When I get a chance, I'll make the page clearer.
Thanks for your concern.

**Comment by anarcat** [comment]
thanks! should i make a pull request?

**Comment by flatcap** [comment]
Thanks, that'd be great if you've got the time.

**Comment by anarcat** [comment]
@flatcap done, turns out it was fairly simple, see #2
