### ISSUE TITLE
neomutt.org/guide/configuration.html broken link

### ISSUE THREAD

**Issue by kotajacob** [neomutt/neomutt.github.io#101]
## Expected Behaviour

Clicking the sample.neomuttrc-starter link on the guide/configuration.html page should take me to the sample configuration located at https://github.com/neomutt/neomutt/blob/master/contrib/samples/sample.neomuttrc-starter

## Actual Behaviour

It instead takes me to https://github.com/neomutt/neomutt/blob/master/contrib/sample.neomuttrc-starter which is a dead link. Appear to have just not been updated.

**Comment by flatcap** [comment]
Thanks
