### ISSUE TITLE
Some newer config variables are not documented on the neomuttrc page

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#111]
I noticed that some config variables are not listed on the web version of the neomuttrc man page[1]. They are, however, listed in (the webversion of) the reference[2]. My local man page has those variables, so I assume that webpage is outdated. Since the reference site lists them, I guess that the current workflow updates the reference website but no the manpage website.

Examples of missing config variables include (I can provide more if needed):
`pager_read_delay`, as well as renames such as `askcc` -> `ask_cc.`

[1] https://neomutt.org/man/neomuttrc
[2] https://neomutt.org/guide/reference.html

**Comment by flatcap** [comment]
I've fixed [a bug](https://github.com/neomutt/neomutt/commit/bff08a1bcf8055a8070a1c04b71133f508c712b6) that was causing the man-page generator to fail, and updated the [man pages](https://neomutt.org/man/neomuttrc).

Thanks!
