### ISSUE TITLE
sample.neomuttrc-starter link broken

### ISSUE THREAD

**Issue by znd4** [neomutt/neomutt.github.io#114]
The [link to the sample neomuttrc config](https://github.com/neomutt/neomutt.github.io/blob/c40c493e6a51ac7fc4a87c661885d620133b1527/guide/configuration.html#L288) is broken.

I'm also not sure if that file exists and, if so, where to find it

**Comment by flatcap** [comment]
Ah!  Good spot.

I've updated the docs in the source repo: https://github.com/neomutt/neomutt/commit/9f3b2f3ce35dbd557f7871bb89e4e7c6b998668b
linked to the [Contrib Repo](https://github.com/neomutt/neomutt-contrib) and [refreshed the website](https://neomutt.org/guide/configuration#quickconfig).

Thanks
