### ISSUE TITLE
Neomutt Guide isn't very searchable

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#12]
I just noticed that the [mutt docs](http://mutt.org/doc/manual/#use-domain) are much easier searchable, because everything is on one page. That means, if i search for the variable `text_flowed`, i can just open the mutt docs and search for the string `text_flowed`, whereas i have to actually read the categories in the neomutt guide to find where its defined.

I like the design of [neomutt.org](neomutt.org), because the categories are actually useful for holding the overview. That means, I'd like to have the functionality of, for instance, the [spacemacs docs](http://spacemacs.org/doc/DOCUMENTATION.html). - there you can search directly, for any string you want. But you have still the categories on the left side to click on, which i found much better.

**Comment by flatcap** [comment]
> mutt docs are much easier searchable, because everything is on one page

Yes, much easier.

> I like the design of neomutt.org

Thanks :-)  It's the best I could do with limited time.

> spacemacs docs. - there you can search directly

Hmm...  That's very nice.
I'd prefer **not** to load the entire manual as one page, but if we _did_, then "spacemacs" is the right way to do it.

According to the internet, it **is** possible to add full-text searching to GitHub Pages.
This would be my preferred solution.

However, both would require someone to do the fiddly work.

<sub>@flatcap quietly admits he searches on a local copy of the all-in-one manual, then gives links to the segmented manual on the web</sub>

**Comment by ghost** [comment]
Maybe we can include sth like [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) into our website?

**Comment by ghost** [comment]
alternative solution: https://github.com/algolia/algoliasearch-jekyll-hyde/blob/master/_config.yml#L36-L45
(demo: https://community.algolia.com/algoliasearch-jekyll-hyde/)
