### ISSUE TITLE
notificate our devel mailinglist with the html errors from travis build

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#16]
Travis provides the possibility of sending the build result to specific email addresses, like described [here](https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications). 

Unfortunately, that doesn't contain the logs of the build (which contain the html errors in our case here) and that's also not changeable. Therefore we need to write a script using a command line mail transfer agent like [S-nail](https://wiki.archlinux.org/index.php/S-nail#I.27m_in.21) or [msmtp](https://wiki.archlinux.org/index.php/Msmtp) (using a mail server like postfix would be an overkill, because its a dockerized environment).

I don't know when I'll have time to do this issue, therefore I post it here.

**Comment by flatcap** [comment]
The current log if 15,000 lines long (540K).
I suggest we fix a few of the problems before enabling automatic emails :-)
