### ISSUE TITLE
skip travis build automatically if non-web things were edited

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#19]
At the moment, we use travis to test the generation of our website. But travis runs at the moment on every commit - even when only the README.md was edited.

Of course we can use [ci skip] in the commit message to tell what to ignore - but some people (including me) keep forgetting that.

Therefore, i think it would be useful, if we introduced a script which reduces the travis build to the files which haven actually been edited. For instance, if we updated the 'README.md`, we don't need to run html-proofer on the website.

i think it would make sense to check also changed markdown files - we can convert them to html using pandoc.

Current Status:
----------------------

* [ ]  Check if files in `man` or `guide` dirs were edited. (Difficult to fix, because manual needs to be manually updated)
    - [ ] Ignore changes in `_man/_generate.sh`
* [ ] Check if the links on the README.md are correct (and not 404)
    - convert it to html using pandoc and run html-proofer on it.
* [ ] Check if the links on the website are correct. (and not 404)

**Comment by toogley** [comment]
i think it would make sense to check also changed markdown files - we can convert them to html using pandoc.

**Comment by ghost** [comment]
moving comments from #31 into this issue:

@toogley
> What maybe needs to be added sometime is to skip the rake test, if the previous build already showed some errors. However, i'm not sure how realistic that is to be implemented, because how can travis/rake know, if the current commit fixes the errors in the last travis build, if not by running the test?

(were deleted in #31)

**Comment by ghost** [comment]
The main idea of this issue was to speed up the travis check - which is already improved by #31 and its followup PR's. Therefore, i think this issue can be closed.
