### ISSUE TITLE
code block inside "Inserting Whitespace for Clarity" is hard to read

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#23]
![screenshot from 2017-02-05 08-54-12](https://cloud.githubusercontent.com/assets/9417950/22624597/d44690fa-eb80-11e6-8cc9-b605297d2ce2.png)

**Comment by flatcap** [comment]
Thanks.  I've tweaked the colours.
That page looks OK and I don't seem to have messed up any other pages.
