### ISSUE TITLE
Neomutt section of neomutt.org/dev/releases page contains broken links

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#24]
Every commit-link in the `Neomutt` section of [neomutt.org/dev/releases](https://www.neomutt.org/dev/releases) is broken.

Sth is wrong with @flatcap 's script, as you link to the commit hash `d8fd0708`  but the correct hash is `4560be576c3b19b6c305d31d1328662b09725fbb`.

**Comment by flatcap** [comment]
****!  Thanks for spotting that.
I trust my ability to script so much that I didn't check my results :-(
