### ISSUE TITLE
List items in Mailing List Guidelines section of newbie tutorial are off

### ISSUE THREAD

**Issue by telshock** [neomutt/neomutt.github.io#38]
The list items on the [Newbie Tutorial](https://www.neomutt.org/dev/newbie-tutorial) are not broken up at the right spots.

```
Mailing List Guidelines
Please:
-     Send emails in plain text, not HTML Use an informative subject line Keep
-     attachments small, or better still: link to the files Remember that we’re
-     volunteers and we may take a while to reply
```

**Comment by flatcap** [comment]
Thanks @telshock, fixed.
(It may take a short while for the cache to expire).

**Comment by telshock** [comment]
That was incredibly quick. Quicker than me being able to figure out how to fork and create a pull request actually :)
