### ISSUE TITLE
Refurbish the site?

### ISSUE THREAD

**Issue by pickfire** [neomutt/neomutt.github.io#4]
> I hate the green background, it looks too contrast.  -- pickfire

**Comment by flatcap** [comment]
I like green, but...
If you are prepared to do the work, you can make it any colour you like :-)

As you've probably seen, the site is built on Jekyll from a mix of Markdown and HTML.
I've got a large collection of ugly scripts that help me keep the docs up-to-date and, importantly, correctly linked.

I like the split / organisation of the pages so far, but I'm open to suggestions.

**Comment by pickfire** [comment]
Why don't we write those pages in markdown? eg. news.html, index.html

I guess it will be a lot easier to maintain if we use markdown.

And **WHAT!!? 246 KB** for just the main site is already overdoing it. I can help to shrink it to ~10KB

Substituting rss image with svg would be a nice idea.

But what is the jquery for? Is it really that important? (it took ⅓ of the size of the site)

I can't even imaging that this site uses bootstrap (by it's appearance), maybe we could void that too by using normalize.css with some custom css.

Maybe those js files isn't required but I am not sure about it.

http://shivamverma.info/2016/04/22/github-corner-text/ Maybe that too or maybe I can write it myself

It would be great too to see the site looks better on mobile (My site looks horrible on mobile too, maybe I could use this chance to improve it)

Maybe we could based it with papercolor like my site too? https://github.com/NLKNguyen/papercolor-theme

Removing the duplicated menu would also be great.

Showing the ugly scripts would help too, I might be able to improve it.

**Comment by flatcap** [comment]
OK, to all your suggestions.
The jquery?  I don't know.  I needed a site and the template came with it.

> bootstrap ... normalize.css ... custom css.

OK
FlatCap enjoys the wooshing noise as things fly over his head :-)

> GitHub corner?

Looks nice.

> site looks better on mobile

Yes, that would be an important change

> papercolor-theme

OK, lovely.

Where do you want to do the development?
I'd rather the site wasn't offline at all.

**Comment by pickfire** [comment]
@flatcap I can do the development at my own computer?

> I'd rather the site wasn't offline at all.

I don't understand what that supposed to means. I guess that you are hosting it yourself (not 24/7)?

**Comment by flatcap** [comment]
> I can do the development at my own computer

ok, great

> > I'd rather the site wasn't offline at all.
> 
> I don't understand what that supposed to means

I just wanted to be clear that you are not editing the current website, but a copy :-)
(The site is hosted by GitHub and some CDN)

Any questions, let me know.
(I'm also in our IRC channel quite a lot: #neomutt on irc.freenode.net)

**Comment by pickfire** [comment]
Okay!

**Comment by ghost** [comment]
@pickfire is this still relevant for you?

**Comment by pickfire** [comment]
@toogley Wow, it looks a lot better now. Sorry that I can't help out much, have stuff to be done.

**Comment by ghost** [comment]
@pickfire no problem :)
