### ISSUE TITLE
Travis builds timed out

### ISSUE THREAD

**Issue by l2dy** [neomutt/neomutt.github.io#43]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
See https://travis-ci.org/neomutt/neomutt.github.io.

**Comment by flatcap** [comment]
It's the link-checker.  It was working fine until I added the [code docs](https://www.neomutt.org/code/) (which are huge).
They take ages to process (and the checker doesn't produce any output whilst it's working) so after 10 minutes, Travis thinks the build has stalled and kills it.

@toogley is it possible to turn on _some_ output to prevent the build being killed?
Alternatively, it might be better to skip the `/code` dir.

**Comment by ghost** [comment]
I'll further investigate this issue to find an appropriate solution (when i have time)

**Comment by ghost** [comment]
Not fixed, but improved drastically by https://github.com/neomutt/neomutt.github.io/commit/c88b8d6d920a4b21436c7b0f7c95aef2c5151bc6.
