### ISSUE TITLE
"No virtual folder, aborting" for '+' bound to generic next-page

### ISSUE THREAD

**Issue by oddhack** [neomutt/neomutt.github.io#44]
I've just upgraded from Debian jessie to stretch and to neomutt 20170113 (1.7.2) as packaged with stretch. My .muttrc has for some years contained

> bind generic + next-page

and, while the new mutt doesn't *complain* about this, typing '+' in the main message index view gives 'No virtual folder, aborting.' instead of going forward a page. By comparison, the similar binding

> bind generic - previous-page

still does what it's supposed to. I see that ':bind index + next-page' in a running instance does what I want, so I'm guessing there were new keybindings added to neomutt somewhere in the patchset. Is this documented, though? I don't see anything obviously relevant in https://www.neomutt.org/changes/user about either 'bind' or 'virtual'. Conceivably this happened in a version of mutt later than that shipped with Debian jessie and just got sucked into neomutt as well, though.

**Comment by flatcap** [comment]
hi @oddhack, sorry we missed you on IRC.

> No virtual folder

That refers to the [NotMuch feature](https://www.neomutt.org/feature/notmuch).
I've just checked and the NeoMutt code doesn't bind `+` by default, thought it suggests it in an example rcfile.

Two possibilities:
You bound the key to a function you don't use and forgot about it :-)
It's a binding in an installed rcfile.

When starting NeoMutt reads the system file `/etc/Muttrc`, then the user config `~/.muttrc` ([it looks for others, too](https://www.neomutt.org/guide/configuration)).

> `bind generic + next-page`

Ah, 'generic' is a bit odd.  It will only get used if the menu doesn't have a specific binding.
If you change your config, I suspect it will work:

`bind index,pager + next-page`

> I don't see anything obviously relevant in https://www.neomutt.org/changes/user 

Thanks for checking :-)

**Comment by oddhack** [comment]
I see that /etc/Muttrc.d/notmuch.rc in the stretch packaging has 'bind index,pager + entire-thread' which is probably the issue. Is that the example rcfile you are thinking of? Maybe the Debian package maintainer included these examples and shouldn't have (well, 'shouldn't' is a strong word, but I don't think a distro packaging needs to include things that the package supplier doesn't themselves use by default, in general).
