### ISSUE TITLE
Arch linux made neomutt part of the official repositories

### ISSUE THREAD

**Issue by doronbehar** [neomutt/neomutt.github.io#51]
The webpage at https://www.neomutt.org/distro/arch needs an update, Arch Linux now added the `neomutt` package in the 'community' repository: [https://www.archlinux.org/packages/community/x86_64/neomutt/](https://www.archlinux.org/packages/community/x86_64/neomutt/).

**Comment by flatcap** [comment]
Yeah!  Great isn't it :-)

@AladW is everything in place?  Are you ready to announce it?

**Comment by AladW** [comment]
#52 

Are there any other files I should edit? The newbie guide only mentions to avoid editing files in `_man` and `guide`

**Comment by flatcap** [comment]
No thanks, that's fine.
If you have any other changes you'd like to make, you can commit then directly
(unless you want a second opinion)

**Comment by AladW** [comment]
Thanks 👍
