### ISSUE TITLE
Make travis test generated html for each build

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#6]
Hey.

I just found [this description on how we could improve our continuous integration ](http://jekyllrb.com/docs/continuous-integration/#the-test-script) service. I think It will be a valuable addition.

[EDIT: the above link initially had a short example for using [html-proofer](https://github.com/gjtorikian/html-proofer)]

**Comment by flatcap** [comment]
Nice find!

**Comment by ghost** [comment]
works since [Commit 24d9a3d](https://github.com/neomutt/neomutt.github.io/commit/24d9a3db4c83692d510278cb9badb3a21152d8e7). The build is still failing, but rather because the resulting html is errorneous.
