### ISSUE TITLE
Rename "Distro Pages" to "Download"

### ISSUE THREAD

**Issue by strk** [neomutt/neomutt.github.io#61]
I've been scanning the page in look for a tarball and felt lost.
A tarball is not even strictly a "Distro" thing anyway...

**Comment by flatcap** [comment]
I take your point.

I've retitled the page to "Downloads"
(it's still called distro.html, but fixing that means breaking links or messing about with redirects)

What you're looking for is on the [GitHub release page](https://github.com/neomutt/neomutt/releases/latest).

From our website that's now:
- Downloads link
- Source code link
- GitHub section

Generally speaking we don't want to encourage people to build their own NeoMutt.
We're a small project and spending time helping people fix their builds isn't a good use of our time.
We have pretty good coverage amongst the distros of Linux and *BSD.

**Comment by strk** [comment]
Thank you. No, I wasn't looking for a github page but for a neomutt.org one :)
