### ISSUE TITLE
HTTPS cert broken

### ISSUE THREAD

**Issue by charlesreid1** [neomutt/neomutt.github.io#67]
the neomutt SSL cert is invalid for https://www.neomutt.org/, and is only valid for a few domains with github in them:

<img width="967" alt="screen shot 2018-05-05 at 18 07 13" src="https://user-images.githubusercontent.com/368075/39668864-3b3c6d74-508f-11e8-89e0-2b00d95bc58f.png">

The SSL cert you are using should be updated to include neomutt.org addresses.

**Comment by flatcap** [comment]
Hi @charlesreid1. thanks for the report.  The new address is (https, no www):

- https://neomutt.org

GitHub recently partnered with Let's Encrypt to provide HTTPS support for custom domains.

I sent out notices to our mailing lists and twitter: saying that I'd dropped the 'www' from the address.
It seems that GitHub haven't added 'www' version to the certificate (and I have no control).
I sent them a support question asking about this, but haven't heard back yet.

(for the last year, I'd been using Cloudflare, as a wrapper, to get HTTPS support)

**Comment by charlesreid1** [comment]
Ah - I see. The URL I was visiting was the one listed on the org's page, not the one listed in this repository's description: https://github.com/neomutt

The neomutt org's URL includes the www.

**Comment by flatcap** [comment]
Ah!  Fixed it.  Thanks.
