### ISSUE TITLE
"To " in %F expando when composing

### ISSUE THREAD

**Issue by x3nb63** [neomutt/neomutt.github.io#69]
_(this is already logged with mutt, but no response so I try here)_

_((if it involves coding I will look into doing it myself as I am about to learn C++, just would need some guidance as I am beginning with that language))_

so I use this hook:

    fcc-save-hook .* =%F

on save it works as expected: `=<recipient name>` is proposed as folder.

On send it sets fcc to `=To <recipient name>`. I do not want that `To ` ("To" plus space) at the beginning. Is there a way to not have it?

**Comment by flatcap** [comment]
> (this is already logged with mutt, but no response so I try here)

Thanks for your honesty (I'm on the mutt mailing lists, too)

There's no workaround, unfortunately.  The `%F` will always display `To: ` or one of the characters from the `$from_chars` (plus a space)

A quick look at the code, shows it wouldn't be too hard to fix:

1. `mutt_index_menu()`
1. `mutt_save_message()`
1. `mutt_default_save()`
1. `addr_hook()`
   Pass a flag from here, asking for a 'plain' name
1. `mutt_make_string_flags()`
   Pass the flag
1. `mutt_expando_format()`
   Pass the flag
1. `index_format_str()`
1. `make_from()`
   Add a flag option to this function

> if it involves coding I will look into doing it myself

great

> as I am about to learn C++, just would need some guidance

If you already know how to program, then I'm happy to direct and answer questions about NeoMutt,
but I don't have time to teach you C :-)

**Comment by flatcap** [comment]
Hmm... I've just realised where this issue is.
You've raised it against the **website**.
Never mind.

**Comment by x3nb63** [comment]
ok, thanks for plotting out the path.

I try. You'll get a patch if I produce something useful.   (... need to build a devel environment first ...)

**Comment by flatcap** [comment]
Debugging NeoMutt can be a bit tricky (being an ncurses app).
There are some notes: https://neomutt.org/dev/debug

**Comment by x3nb63** [comment]
nice, exactly the thing I need to learn.

**Comment by x3nb63** [comment]
here it is: https://github.com/x3nb63/neomutt/commit/581fa91c0575da502b3f5f6ab99e95be11e6f9a7

its _works-for-me_ state, only briefly tested and I have questions:

* the flag is called MUTT_FORMAT_PLAIN, given that name it would be logical to apply it to DISP_CC, DISP_BCC, and DISP_FROM as well, right?

* this alters how %F expando works, thus people who want "To " lose it. Better make it a new expando?

(btw: your list of functions kept me searching the code down to a minimum, thanks!)

**Comment by flatcap** [comment]
That seems like a reasonable start.
Yes, I think a new expando might be a good idea.

Please can you open a Pull-Request -- there should be button when you view your repo.
Then I'll be able to review your code (and others too).
