### ISSUE TITLE
To fork, or not to fork

### ISSUE THREAD

**Issue by rjc** [neomutt/neomutt.github.io#70]
Hi,

Whilst most things in life aren't black and white, the distinction of whether a project *is* or is *not* a fork, should be straightforward. After going through issues[0] and pull requests[1], I can't find a definitive answer on whether NeoMutt is a fork of Mutt or not, especially since your own website[2] states:

> What is it?
> NeoMutt is a command line mail reader (or MUA). It's a fork of Mutt with added **features**. *Read more...**

and then ***Read more...*** link[3] goes on to *contradict* it:

> Is it a Fork?
> It's **not a fork** of Mutt.

I'd appreciate if you could come to an agreement internally and reflect it on your website, please.

Cheers,

Raf

[0]: https://github.com/neomutt/neomutt/issues/1075
[1]: https://github.com/neomutt/neomutt/pull/1138
[2]: https://neomutt.org/#overview
[3]: https://neomutt.org/about.html#is-it-a-fork

**Comment by flatcap** [comment]
hehe, that represents my unwillingness to commit :-)
In every practical sense, we're a fork.  I'll update the docs.

**Comment by rjc** [comment]
**Not** what I was hoping for ;^) 

Nevertheless, thanks for clarifying!

**Comment by flatcap** [comment]
I'd have preferred that too, but upstream Mutt are very conservative when accepting change.

Besides the features, we've been working aggressively to tidy and document the code (which is mess), to make future development simpler.  We're looking ahead, far ahead.  Mutt isn't.
