### ISSUE TITLE
SSL certificate domain

### ISSUE THREAD

**Issue by alerque** [neomutt/neomutt.github.io#72]
There are some weblinks out there pointing to neomutt.org, but the SSL certificate does not include this domain. Either that domain should somehow forward to the neomutt.github.io address (without an intermediate SSL error) or the canonical domain should be updated. Right now lots of users are just blocked from reaching the site due to the error.

**Comment by flatcap** [comment]
Hi @alerque 

> pointing to neomutt.org

Did you mean www.neomutt.org ?

We dropped the 'www' over two months ago, when GitHub adopted Let's Encrypt.
The certificate covers 'neomutt.org', but not the 'www.' part.
GitHub only allows us one or the other (even though LE now supports wildcard certs)

> domain should somehow forward

Unfortunately, we don't have any control over that: GitHub host the site.
You can't view the bare: neomutt.github.io address.

> Right now lots of users are just blocked from reaching the site due to the error.

Sorry.  We did our best to notify everyone in advance.
We fixed all of our links and prompted everyone to do the same.

**Comment by alerque** [comment]
It appears I was following a link where the user facing text was `neovim.org` but the href was hard coded to `www.neomutt.org`. I added a security exception to load that domain to see what was going on but did not then notice that it forwarded me to `neovim.org` where the cert was correct. I understand there is not much you can do about that issue, please disregard.
