### ISSUE TITLE
Enhancement: FAQ / Minimal debugging

### ISSUE THREAD

**Issue by 927589452** [neomutt/neomutt.github.io#78]
An section with easy minimal debug ideas would be very useful

for example trying 
``` neomutt -F /dev/null ``` 
to test if it is a misconfiguration or a 'real' bug

suggesting purging all caches

**Comment by flatcap** [comment]
That's a good idea.
Unfortunately, I'm really busy trying to make some big architectural changes and there doesn't seem to be anyone else to help.

Would you be interested in starting the page?
(the website is written in Markdown)
