### ISSUE TITLE
Suggest useful programs

### ISSUE THREAD

**Issue by Konfekt** [neomutt/neomutt.github.io#79]
Suggest on https://neomutt.org/contrib/useful-programs

- [mail-query](https://github.com/pbrisbin/mail-query) as a query tool
- [mutt-alias.sh](https://github.com/Konfekt/mutt-alias.sh) to add aliases for all e-mail addresses found in a maildir
- [mutt-trim](https://github.com/Konfekt/mutt-trim) to unclutter and normalize quoted text in an e-mail
- [vcalendar-filter](https://github.com/terabyte/mutt-filters/blob/master/vcalendar-filter) to view calendar files (ics)
- [mutt2khal](https://github.com/pimutils/khal/blob/master/misc/mutt2khal) for passing calendar items to the command-line calendar [khal](https://github.com/pimutils/khal),

and the address book

- [khard](https://github.com/scheibler/khard) to synchronize address books between your PC and mobile device with [vdirsyncer](https://github.com/untitaker/vdirsyncer).

and the Vim plug-ins

- [vim-mutt-aliases](https://github.com/Konfekt/vim-mutt-aliases/) to complete mail aliases in Vim
- [vim-mailquery](https://github.com/Konfekt/vim-mailquery) to complete mail addresses in your inbox in Vim

**Comment by flatcap** [comment]
[added](https://neomutt.org/contrib/useful-programs)

If you have any other suggestions, you can [edit the file in GitHub](https://github.com/neomutt/neomutt.github.io/blob/master/_contrib/useful-programs.md), at the press of a button.

Thanks.

**Comment by Konfekt** [comment]
> If you have any other suggestions, you can edit the file in GitHub, at the press of a button.

Thanks for pointing that out. The contribution site https://neomutt.org/contrib.html says, though:

 > If you are a GitHub user, you can raise a NeoMutt issue to tell us about your idea. Or, you can contact the lead developer, Richard Russon <rich@flatcap.org> 

I opened the pull request https://github.com/neomutt/neomutt.github.io/pull/80 to add that direct route.
