### ISSUE TITLE
driver tags pattern

### ISSUE THREAD

**Issue by civic9** [neomutt/neomutt.github.io#90]
On https://neomutt.org/guide/advancedusage.html#patterns
```~Y EXPR ```
is missing.
It is implemented 
https://github.com/neomutt/neomutt/blob/260d7248411592ce718d2fd661e959bb020ba6e2/pattern.c#L1337
and works fine for me with IMAP (without notmuch).

**Comment by flatcap** [comment]
Well spotted, @civic9 
Fixed: https://github.com/neomutt/neomutt/commit/d63c3caaf43cf7a343f339f1194f5dd1217694f4, https://github.com/neomutt/neomutt.github.io/commit/5864ca9fdbf426604751480f8ddc0db986c4145d
Thanks.
