### ISSUE TITLE
Can add some introductions about these colorscheme of mutt?

### ISSUE THREAD

**Issue by Freed-Wu** [neomutt/neomutt.github.io#92]
in the website there are many introduction about project related to mutt. perhaps some colorschemes will be needed. it is a suggestion. Thanks!

**Comment by flatcap** [comment]
Yes, that would be nice.
Are you offering to write an introduction?

**Comment by Freed-Wu** [comment]
with pleasure. let me take a look at this jekyll!

**Comment by flatcap** [comment]
> with pleasure

Brilliant, thanks.
If you write it in Markdown, then I can put it straight onto the website.

> let me take a look at this jekyll!

If you've used Ruby before, it should be fairly simple.
(If not, don't worry)

```sh
gem install github-pages
gem install jekyll-algolia
```

Then clone this repo and serve:
```
git clone https://github.com/neomutt/neomutt.github.io
cd neomutt.github.io
jekyll serve
```

which will start a local webserver at: http://127.0.0.1:4000/
