### ISSUE TITLE
Broken link in /changes/devel

### ISSUE THREAD

**Issue by louis77** [neomutt/neomutt.github.io#97]
I found a broken link to a non-existing file `CONTRIBUTING.md` in the [/changes/devel](https://neomutt.org/changes/devel) page.
I think it should point to the awesome [/dev/newbie-tutorial](https://neomutt.org/dev/newbie-tutorial) page.

Also, since the neomutt site is hosted on GitHub Pages, there is the `github-pages` Gem plugin missing in the Gemfile. Without it, it is difficult to get all the right versions of the Jekyll gems with bundler. 

I'll send a PR for review.

**Comment by flatcap** [comment]
Thanks.

I used to have (the Rakefile is still there) an automatic link-checker that ran on every commit,
but not long back GitHub started rate-limiting access, so the checked kept failing.
I'm not sure if there's a way around that.

As for `github-pages`, I only learnt about that recently -- I'm a Ruby newbie -- I didn't think to add it to the repo itself.
